### ISSUE TITLE
Is there a way to parse lists

### ISSUE THREAD

**Issue by NitinSRKalavala** [tlsa/libcyaml#107]
Yaml supports lists in its values. Is there a way to use libcyaml to parse something like this?

games:
  game1:
  - id: 0
    name: Player1
    data:
    - 'x', 1, 0, 9

**Comment by tlsa** [comment]
Yes, they're called sequences in YAML.

For the `data` sequence in your example, you have an `x` character and some numbers.

In libcyaml, everything is controlled by a typing schema, so all the entries of a sequence (or list) have to have the same type.

You could load your example if the data type for the sequence entries was a character.

I'm closing this because libcyaml supports sequences.  Please comment if you can't get it working.

**Comment by tlsa** [comment]
The example in the tutorial uses a sequence: https://github.com/tlsa/libcyaml/blob/master/docs/guide.md

**Comment by tlsa** [comment]
The example in the tutorial uses a sequence: https://github.com/tlsa/libcyaml/blob/master/docs/guide.md
