### ISSUE TITLE
use `make check` instead of `make test`

### ISSUE THREAD

**Issue by alex-tee** [tlsa/libcyaml#115]
`check` is the standard target for running tests

https://www.gnu.org/software/make/manual/make.html#Standard-Targets

**Comment by tlsa** [comment]
`check` is the standard for GNU projects, and anything using autotools, but libcyaml isn't a GNU project and doesn't use autotools.

I believe CMake and Meson use `test`.

Do you see any advantages for changing beyond simply familiarity for people used to working with GNU projects?  Personally I'm familiar with `test` because it's used in NetSurf's buildsystem.

**Comment by alex-tee** [comment]
well, besides familiarity, cyaml would integrate easily into packaging systems that assume a standard "formula" for Makefile-based projects (`make` -> `make check` -> `make install`). it basically makes packagers' lives a bit easier. other than that it's just preference i guess.

for meson and cmake, they have their own standards and they pretty much apply to all cmake or meson projects, but this Makefile is too unique IMO so I'd make it at least somewhat compatible with the standard GNU procedure for build -> test -> install

a `check: test` rule would probably work

**Comment by tlsa** [comment]
I don't really like the idea of treating it as a GNU/autotools project when it isn't.  It sounds like sloppy packaging.  Anyway, I'll add `check` as an alias for the `test` target.  Note, none of the verbosity variants will work for the `check` alias.

**Comment by tlsa** [comment]
Released in [v1.0.2](https://github.com/tlsa/libcyaml/releases).
