### ISSUE TITLE
Compilation error when trying to use in C++ project

### ISSUE THREAD

**Issue by AlexPortland** [tlsa/libcyaml#118]
I did a small demo project (visual studio 2019) in C to read a yml file, and it worked fine.
I tried to use the same code in C++ project (__cplusplus flag is ON). Just by adding the libcyaml files everything is OK and compiling, but when I try to create the schema structs it raises an error in the macro functions that the enum value I chose (CYAML_FLAG_DEFAULT) is actually an int and int cannot be used to initialized an entity of type "cyaml_flag". The same exact code works fine when I replace the file extension from cpp to c.

**Comment by tlsa** [comment]
I think it's because the CYAML schema-building helper macros (e.g. [CYAML_VALUE_INT](https://github.com/tlsa/libcyaml/blob/60234a8af8ff738905c6cf27d0af0ea4249410fa/include/cyaml/cyaml.h#L559)) are implemented using a C99 feature called "designated initializers".

This allows structures be initialized using `.member` to reference structure members.  Without it, structures are initialized as a comma separated list, which is order-dependent and error prone.

I don't think C++ got designated initializers until C++20.  So you could either try with C++20, if that's possible for your project, or you could try without using those schema-building helper macros, and just use the old style of structure initialization.

**Comment by tlsa** [comment]
You could also put the YAML loading saving stuff in a C file, containing all the C-style macros, and create a header exposing your load/save functions, and just call those from the C++ code.

**Comment by AlexPortland** [comment]
The latter worked great!
Thanks.
