### ISSUE TITLE
load_data uses uint8_t pointer while save_data uses char pointer

### ISSUE THREAD

**Issue by mohmacht** [tlsa/libcyaml#124]
I think the two functions should use the same types for consistency

**Comment by tlsa** [comment]
I think my intention with this was that the library would attempt to load any arbitrary byte sequence (hence `uint8_t`), but it would always save to a valid UTF-8 string (hence `char`).

I'm unwilling to change this now, because code has already been written against the existing API. If it is changed it could generate new warnings in client code about mismatched signs for certain platforms. (On some platforms, `char` is signed, and on others it is unsigned.)

I will reconsider this when I have enough changes for a more drastic breaking change, which would warrant a v2.0.0 release.
