### ISSUE TITLE
how to use double type in libcyaml

### ISSUE THREAD

**Issue by AOOOOOA** [tlsa/libcyaml#125]
Hi Tlsa:
 I want to use double type in libcyaml since I want to read some double type data from my .yml. However,I only find cyml_float in cyaml.h. How can I achieve that? Thank you so much!

**Comment by tlsa** [comment]
Hi,

The [CYAML_FLOAT](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L73) type works for both the C `float` and `double` types.

It's the same as e.g. [CYAML_UINT](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L55) working for `uin64_t`, `unsigned`, `uint8_t`, etc.

It works because libcyaml is told the size of the value.  See the comment for the [data_size](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L309) member of `cyaml_schema_value_t`.

There are examples of using doubles in the unit tests, which are quite self-contained.

https://github.com/tlsa/libcyaml/blob/master/test/units/load.c#L440

Hope this helps!

**Comment by AOOOOOA** [comment]
Hi Tlsa:
 After I tried, I found out that I didn't make it clear in the former question description. I have a sequence consist of double data in .yml. I will show it in img below. I check the example in the link you gave, it is like a single data which can be read in mapping_float format. However, I have to achieve read data both in sequence and double format?
  Below is the code , .yml and the terminal output. The code is the numerical example code, I just change some TYPE into double and float. I wish the output data has the same length as it in .yml.  I just wondering the problem is become from the CYAML_FIELD_SEQUENCE?

<img width="490" alt="cyaml_float_code" src="https://user-images.githubusercontent.com/38175747/79949914-e041c400-84a8-11ea-9149-af6b3e9456a1.PNG">
<img width="269" alt="捕获" src="https://user-images.githubusercontent.com/38175747/79950177-3c0c4d00-84a9-11ea-8ace-615817c10286.PNG">
<img width="92" alt="k" src="https://user-images.githubusercontent.com/38175747/79950184-3f073d80-84a9-11ea-944c-36a62bac9855.PNG">

Thank you so much for your time! I appreciate your reply!

**Comment by AOOOOOA** [comment]
> Hi,
> 
> The [CYAML_FLOAT](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L73) type works for both the C `float` and `double` types.
> 
> It's the same as e.g. [CYAML_UINT](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L55) working for `uin64_t`, `unsigned`, `uint8_t`, etc.
> 
> It works because libcyaml is told the size of the value. See the comment for the [data_size](https://github.com/tlsa/libcyaml/blob/master/include/cyaml/cyaml.h#L309) member of `cyaml_schema_value_t`.
> 
> There are examples of using doubles in the unit tests, which are quite self-contained.
> 
> https://github.com/tlsa/libcyaml/blob/master/test/units/load.c#L440
> 
> Hope this helps!

Hi Tlsa: 
I add some new problems in this comment. Sorry that I forget to quote reply.

**Comment by tlsa** [comment]
How's this: https://github.com/tlsa/libcyaml/pull/127?

**Comment by AOOOOOA** [comment]
> How's this: #127?

Thank you! The problem is solved!

**Comment by tlsa** [comment]
I've released [LibCYAML v1.1.0](https://github.com/tlsa/libcyaml/releases) which contains this change.
