### ISSUE TITLE
Slow to load large files

### ISSUE THREAD

**Issue by yjiang2021** [tlsa/libcyaml#129]
It is very slow to load large files, for example, it takes more than 3 minutes for a 30 MB file. Is this expected? Do you have any suggestion to improve the performance? This is with an x86/Linux machine. Thanks!

**Comment by tlsa** [comment]
Wow, I've never tried to load such big files!

The things that might be slow are:

1. Looking up mapping keys in your mapping schema arrays.  (Do you have mappings with a lot of different fields?  If some are optional, it would be more optimal to put the required fields first in the arrays.)
2. Sequences with many entries could cause a lot of realloc() churn.

If it's the first, there are things that could be done to optimise mapping schema lookup.  With a bit of work up-front we could make all lookups much faster.

If the second the number of reallocs could be simply reduced. (It's currently one for each new entry for simplicity, and because the realloc implementation usually does the obvious optimisation behind the scenes anyway.)

The best way to find out would be to profile it.  Could you run your application under `valgrind --tool=callgrind` with a debug build of LibCYAML?  Alternatively, could you share your CYAML schema code and the file you're loading?

**Comment by yjiang2021** [comment]
Thanks for the info, I will do some experiments. Attached is a zip file containing the schema code and the yaml file. Your help is greatly appreciated!
[load_yaml.tar.gz](https://github.com/tlsa/libcyaml/files/4720703/load_yaml.tar.gz)

**Comment by yjiang2021** [comment]
To compile: "gcc load_yaml_file.c -o load -L<lib-path> -lcyaml", to run: "load <the yaml file>".

**Comment by yjiang2021** [comment]
to run: "load file-name".

**Comment by tlsa** [comment]
I've profiled it, thanks!  It seems 98.97% of the time is spent in the alias/anchor handling.

I'll look at optimising it this weekend!  Thanks for the report, and the test files!

**Comment by yjiang2021** [comment]
Great. Thank you very much Michael!

**Comment by tlsa** [comment]
Please try with the [tlsa/optimise-anchors](https://github.com/tlsa/libcyaml/commits/tlsa/optimise-anchors) branch.  When you build the branch, use `make VARIANT=release` or `make VARIANT=release install` to build the library with compiler optimisation enabled.  See the README for more about how to build.

On my laptop, with your test file, I see a significant speedup over master:

| Branch                  | `VARIANT=debug` | `VARIANT=release` |
| ----------------------- | --------------- | ----------------- |
| `master`                | 8m 51.088s      | 3m 12.613s        |
| `tlsa/optimise-anchors` | 2.773s          | 1.843s            |

**Comment by yjiang2021** [comment]
I tested on my setup, it takes about 2 seconds now, huge speedup! Thank you very much for your help and the quick turnaround, really appreciate it!

**Comment by tlsa** [comment]
I made a few slight further improvements and merged it to master.

I'm hoping to make a new release this weekend.

**Comment by tlsa** [comment]
I've released [LibCYAML v1.1.0](https://github.com/tlsa/libcyaml/releases) which contains this optimisation.

**Comment by yjiang2021** [comment]
Great. Thank you Michael!
