### ISSUE TITLE
Read a field which is not fixed/known-name

### ISSUE THREAD

**Issue by aniruddha-a** [tlsa/libcyaml#161]
Hello,

I am trying to use `libcyaml` to parse OpenAPI based YAML, which has contents like this

```
paths:
  /pet:       <--- this can be any path!
    post:      <-- this can  be one of post/put/patch/delete/get
      summary: Add a new pet to the store
      description: Add a new pet to the store
      operationId: addPet
      responses:
        '200':
          description: Successful operation
          content:
            application/xml:
              schema:
```

How can I add a schema/definition to parse this  ? From reading the example, I got the parsing part
when there is like `name: value` and `name` is known in advance. How do I define rules when I dont
know the _word_/_key_ in advance?

Thanks.

**Comment by tlsa** [comment]
Hi @aniruddha-a,

I'm afraid it is just not designed for that use case.  All keys must be something that is known up-front, so that the schema can be looked by by name.  I would either use libyaml directly, or if possible, adapt the YAML to have a fixed-form.  For example, something like this:

```yaml
paths:
- path: /pet
  kind: post
  summary: Add a new pet to the store
  description: Add a new pet to the store
  operationId: addPet
  responses:
   ...
```

Hope that helps!

**Comment by aniruddha-a** [comment]
Oh! :(
This is a standardized YAML that I am trying to parse, so the format is not in my control.
Is there any way that I can hack some change in `libcyaml` to do this - if  its possible, I 
can spend some time and check the code. If its not possible, then I will use `libyaml` directly.
But so far, I love `libcyaml` and want to continue using it if there is a way out.

Thank you.

**Comment by danielealbano** [comment]
Very hacky but you can potentially drop the first 2 lines and then drop the
initial spaces from all the lines before parsing the data with cyaml.

**Comment by tlsa** [comment]
@aniruddha-a 

> This is a standardized YAML that I am trying to parse, so the format is not in my control.

In that case, I would use `libyaml`!

Sorry I can't be more help! :crying_cat_face:

> Is there any way that I can hack some change in `libcyaml` to do this - if its possible, I
> can spend some time and check the code.

I can think of one hideous workaround, which I would not be prepared to support.  If the unknown keys in the struct all have the same value type, you could possibly adapt the code so that [on this line](https://github.com/tlsa/libcyaml/blob/6f2ad8b1278853e0cf2ee9a4ae8bc3179dd532ec/src/load.c#L798) it returns `0`, and ensure that the schema mapping field array definition has the value for the arbitrary string key as the first array element.  In the schema, the name you put for the key for this field would not matter.  This would break a lot of `libcyaml`'s checks of the input YAML format validity.  So it would fail to reject malformed YAML.  Also it might not solve all the problems of your input YAML structure anyway.
